controllers/ActorController.php
<?php

namespace app\controllers;

use app\models\actor\Actor;
use Yii;

/**
 * ActorController implements the CRUD actions for Actor model.
 */
class ActorController extends CrudController
{
    public function init()
    {
        $this->modelClass = Actor::className();
        parent::init();
    }
}

controllers/AuthController.php
<?php
/**
 * Created by PhpStorm.
 * User: Артем
 * Date: 04.12.2015
 * Time: 12:42
 */

namespace app\controllers;


use app\models\user\web\SignInForm;
use app\models\user\web\SignUpForm;
use Yii;
use yii\web\Controller;

class AuthController extends Controller
{
    public function actionSignIn()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goBack();
        }

        /** @var SignInForm $model */
        $model  = Yii::createObject(SignInForm::className());

        if ($model->load(Yii::$app->request->post()) && $model->signIn()) {
            return $this->goBack();
        }

        return $this->render('sign-in', [
            'model' => $model
        ]);
    }

    public function actionSignUp()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goBack();
        }

        /** @var SignUpForm $model */
        $model = Yii::createObject(SignUpForm::className());

        if ($model->load(Yii::$app->request->post()) && $model->signUp()) {
            return $this->goBack();
        }

        return $this->render('sign-up', [
            'model' => $model
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect($this->goHome());
    }
}

controllers/CountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\country\Country;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends CrudController
{
    public function init()
    {
        $this->modelClass = Country::className();
        parent::init();
    }
}

controllers/CrudController.php
<?php

namespace app\controllers;

use Yii;
use yii\base\InvalidConfigException;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CrudController extends Controller
{
    /**
     * Название класса ActiveRecord, для которого будут реализованы
     * CRUD операции
     * @var string|ActiveRecord
     */
    protected $modelClass;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    public function init()
    {
        parent::init();

        if (is_null($this->modelClass)) {
            throw new InvalidConfigException('You must set model class');
        }
    }

    public function actionIndex()
    {
        /** @var ActiveRecord $modelClass */
        $modelClass = $this->modelClass;
        $dataProvider = new ActiveDataProvider([
            'query' => $modelClass::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        /** @var ActiveRecord $model */
        $model = new $this->modelClass;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        /** @var ActiveRecord $model */
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return ActiveRecord
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        /** @var ActiveRecord $modelClsas */
        $modelClsas = $this->modelClass;
        if (($model = $modelClsas::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/DirectorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\director\Director;

/**
 * DirectorController implements the CRUD actions for Director model.
 */
class DirectorController extends CrudController
{
    public function init()
    {
        $this->modelClass = Director::className();
        parent::init();
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
}

controllers/VideoController.php
<?php
namespace app\controllers;

use app\models\image\web\ImageUploadForm;
use app\models\video\Video;
use app\models\video\web\ComplexVideoForm;
use app\models\video\web\VideoForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class VideoController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        $dataProvider = Yii::createObject(ActiveDataProvider::className(), [[
            'query' => Video::find()
        ]]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionCreate()
    {
        $model = Yii::createObject(ComplexVideoForm::className(), [[
            'video' => Yii::createObject(VideoForm::className(), [Yii::createObject(Video::className())]),
            'pic' => Yii::createObject(ImageUploadForm::className())
        ]]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    public function actionUpdate($id)
    {
        $model = Yii::createObject(ComplexVideoForm::className(), [[
            'video' => Yii::createObject(VideoForm::className(), [$this->findVideo($id)]),
            'pic' => Yii::createObject(ImageUploadForm::className())
        ]]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model
        ]);
    }

    public function actionDelete($id)
    {
        $this->findVideo($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return Video
     * @throws NotFoundHttpException
     */
    private function findVideo($id)
    {
        if ($video = Video::findOne($id)) {
            return $video;
        }

        throw new NotFoundHttpException('Video not found');
    }
}

views/actor/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\actor\Actor */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="actor-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/actor/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\actor\Actor */

$this->title = 'Create Actor';
$this->params['breadcrumbs'][] = ['label' => 'Actors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="actor-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/actor/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Actors';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="actor-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Actor', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/actor/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\actor\Actor */

$this->title = 'Update Actor: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Actors', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="actor-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/actor/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\actor\Actor */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Actors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="actor-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>

views/country/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\country\Country */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/country/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\country\Country */

$this->title = 'Create Country';
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/country/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Countries';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Country', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/country/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\country\Country */

$this->title = 'Update Country: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="country-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/country/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\country\Country */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>

views/director/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\director\Director */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="director-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/director/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\director\Director */

$this->title = 'Create Director';
$this->params['breadcrumbs'][] = ['label' => 'Directors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="director-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/director/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Directors';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="director-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Director', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

</div>

views/director/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\director\Director */

$this->title = 'Update Director: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Directors', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="director-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/director/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\director\Director */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Directors', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="director-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Видео', 'url' => ['video/index']],
            ['label' => 'Словари', 'items' => [
                ['label' => 'Страны', 'url' => ['country/index']],
                ['label' => 'Актеры', 'url' => ['actor/index']],
                ['label' => 'Режиссеры', 'url' => ['director/index']],
            ]],
            Yii::$app->user->isGuest ?
                ['label' => 'Войти', 'url' => ['auth/sign-in']] :
                [
                    'label' => 'Выйти',
                    'url' => ['/auth/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/video/_form.php
<?php
/** @var $model \app\models\video\web\ComplexVideoForm*/
use app\models\video\web\VideoForm;
use app\widgets\RangeListWidget;
use kartik\date\DatePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);

?>

<?=$this->render('_form_video', [
    'model' => $model->video,
    'form' => $form
])?>

<?=$this->render('_form_pic', [
    'model' => $model->pic,
    'form' => $form
])?>

<?= Html::submitButton($model->isCreationForm() ? 'Создать' : 'Обновить')?>

<?php if ($pic = $model->video->getVideoRecord(false)->getPic()): ?>
    <h3>Pics</h3>
    <?=Html::a('Origin Pic', $pic->getOriginPath())?>
    <?php foreach ($pic->getThumbnailPaths() as $kind => $thumbPath):?>
        <?=Html::a($kind . ' Pic', $thumbPath)?>
    <?php endforeach;?>
<?php endif;?>

<?php $form->end(); ?>

views/video/_form_pic.php
<?php
/** @var \app\models\image\web\ImageUploadForm model */
/** @var \yii\widgets\ActiveForm $form */
?>

<?=$form->field($model, 'imageFile')->fileInput(['accept' => 'image/*'])?>

views/video/_form_video.php
<?php
/** @var VideoForm $model */

use app\models\video\web\VideoForm;
use app\widgets\RangeListWidget;
use kartik\date\DatePicker;

?>

<?= $form->field($model, 'title')?>

<?= $form->field($model, 'originTitle')?>

<?php
$rangeListOptions = [
    'min' => VideoForm::MIN_FILMING_PERIOD_YEAR,
    'max' => VideoForm::MAX_FILMING_PERIOD_YEAR,
    'step' => 1
];
?>
<?=$form->field($model, 'yearStartFilming')->widget(RangeListWidget::className(), $rangeListOptions)?>
<?=$form->field($model, 'yearEndFilming')->widget(RangeListWidget::className(), $rangeListOptions)?>

<?=$form->field($model, 'duration')?>

<?=$form->field($model, 'premiereDate')->widget(DatePicker::className(), [
    'pluginOptions' => [
        'format' => 'dd.mm.yyyy'
    ]
])?>,

<?=$form->field($model, 'annonce')->textarea()?>

<?=$form->field($model, 'description')->textarea()?>

<?=$form->field($model, 'actorIds')->checkboxList($model->getActorList())?>

<?=$form->field($model, 'directorId')->dropDownList($model->getDirectorList())?>

<?=$form->field($model, 'countryId')->dropDownList($model->getCountryList())?>

views/video/create.php
<h1>Добавить видео</h1>

<?=$this->render('_form', [
    'model' => $model
])?>

views/video/index.php
<?php
/** @var $dataProvider \yii\data\ActiveDataProvider */
use app\models\image\Pic;
use app\models\video\Video;
use yii\grid\GridView;
use yii\grid\SerialColumn;
use yii\helpers\Html;

?>

<?= Html::a('Добавить новое видео', ['video/create'], ['class' => 'btn btn-primary'])?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => SerialColumn::className(),],
        [
            'label' => 'Название фильма',
            'attribute' => 'title'
        ],
        [
            'label' => 'Оригинальное название',
            'attribute' => 'origin_title',
        ],
        [
            'label' => 'Годы съемок',
            'attribute' => 'year_start_filming',
            'value' => function (Video $model) {
                return $model->year_start_filming . ' - ' . $model->year_end_filming;
            }
        ],
        [
            'label' => 'Продолжительность (секунд)',
            'attribute' => 'duration',
        ],
        [
            'label' => 'Дата премьеры',
            'attribute' => 'premiere_date',
            'value' => function (Video $model) {
                return $model->getPremiereDate()->format('d.m.Y');
            }
        ],
        [
            'label' => 'Облолжка',
            'value' => function (Video $model) {
                if ($pic = $model->getPic()) {
                    $img = Html::img($pic->getThumbnailPath(Pic::THUMBNAIL_SMALL));
                    return Html::a($img, $pic->getOriginPath());
                } else {
                    return null;
                }
            },
            'format' => 'raw'
        ],
        [
            'class' => \yii\grid\ActionColumn::className(),
            'template' => '{update} {delete}'
        ]
    ]
])?>

views/video/update.php
<h1>Обновить видео</h1>

<?=$this->render('_form', [
    'model' => $model
])?>